"""Fixed CampusName length from 30 to 255

Revision ID: 1b12c1378a95
Revises: 25c74000fabc
Create Date: 2026-07-31 23:23:47.804436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b12c1378a95'
down_revision: Union[str, Sequence[str], None] = '25c74000fabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Campus', 'CampusName',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Campus', 'CampusName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
