"""Fixed CampusName length from 3 to 30

Revision ID: 25c74000fabc
Revises: 8b154e749da6
Create Date: 2026-07-31 00:38:41.011932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c74000fabc'
down_revision: Union[str, Sequence[str], None] = '8b154e749da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Campus', 'CampusName',
               existing_type=sa.VARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Campus', 'CampusName',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
