"""Change floorcode to not unique

Revision ID: 363f53b4921f
Revises: 1b12c1378a95
Create Date: 2026-07-31 23:41:49.283438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363f53b4921f'
down_revision: Union[str, Sequence[str], None] = '1b12c1378a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Room', 'RoomType',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_constraint('UQ__Floor__394E956ABD8D6031', 'Floor', type_='unique')
    op.drop_constraint('UQ__Room__4F9D52316E237DA2', 'Room', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Room', 'RoomType',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.create_unique_constraint('UQ__Floor__394E956ABD8D6031', 'Floor', ['FloorCode'])
    op.create_unique_constraint('UQ__Room__4F9D52316E237DA2', 'Room', ['RoomCode'])
    # ### end Alembic commands ###
