"""Merged User and Staff table into one and added boolean default value

Revision ID: 4a4b3fb51460
Revises: 9013ba5ba29c
Create Date: 2026-08-26 17:10:54.732507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4b3fb51460'
down_revision: Union[str, Sequence[str], None] = '9013ba5ba29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK__Assignmen__Clean__625A9A57'), 'Assignment', type_='foreignkey')
    op.drop_constraint(op.f('FK__Assignmen__Super__65370702'), 'Assignment', type_='foreignkey')
    op.drop_table('Staff')
    op.create_foreign_key(None, 'Assignment', 'User', ['SupervisorID'], ['UserID'])
    op.create_foreign_key(None, 'Assignment', 'User', ['CleanerID'], ['UserID'])
    op.add_column('User', sa.Column('Role', sa.String(length=20), nullable=False))
    op.add_column('User', sa.Column('Category', sa.String(length=30), nullable=True))
    op.add_column('User', sa.Column('CompanyID', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('ZoneID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'User', 'Zone', ['ZoneID'], ['ZoneID'])
    op.create_foreign_key(None, 'User', 'Company', ['CompanyID'], ['CompanyID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'ZoneID')
    op.drop_column('User', 'CompanyID')
    op.drop_column('User', 'Category')
    op.drop_column('User', 'Role')
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Assignmen__Super__65370702'), 'Assignment', 'Staff', ['SupervisorID'], ['UserID'])
    op.create_foreign_key(op.f('FK__Assignmen__Clean__625A9A57'), 'Assignment', 'Staff', ['CleanerID'], ['UserID'])
    op.create_table('Staff',
    sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Role', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Category', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CompanyID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ZoneID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CompanyID'], ['Company.CompanyID'], name=op.f('FK__Staff__CompanyID__4D5F7D71')),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name=op.f('FK__Staff__UserID__4E53A1AA')),
    sa.ForeignKeyConstraint(['ZoneID'], ['Zone.ZoneID'], name=op.f('FK__Staff__ZoneID__4F47C5E3')),
    sa.PrimaryKeyConstraint('UserID', name=op.f('PK__Staff__1788CCACD49520C6'))
    )
    # ### end Alembic commands ###
