"""Change to nullable for area and epu in room

Revision ID: 54b88084d6e3
Revises: afbb91682c4f
Create Date: 2026-08-02 17:57:47.454573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b88084d6e3'
down_revision: Union[str, Sequence[str], None] = 'afbb91682c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Room', 'RoomArea',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
    op.alter_column('Room', 'RoomEPU',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Room', 'RoomEPU',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
    op.alter_column('Room', 'RoomArea',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
    # ### end Alembic commands ###
