"""Set CompanyID and ZoneID nullable in User table

Revision ID: 67c7d2a7f6b4
Revises: 4a4b3fb51460
Create Date: 2026-08-27 14:39:25.212684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c7d2a7f6b4'
down_revision: Union[str, Sequence[str], None] = '4a4b3fb51460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'CompanyID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('User', 'ZoneID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'ZoneID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('User', 'CompanyID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
