"""Create tables

Revision ID: 8b154e749da6
Revises: 
Create Date: 2026-07-30 14:47:43.107635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '8b154e749da6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campus',
    sa.Column('CampusCode', sa.String(length=3), nullable=False),
    sa.Column('CampusName', sa.String(length=3), nullable=False),
    sa.Column('State', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('CampusCode')
    )
    op.create_table('Company',
    sa.Column('CompanyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CompanyName', sa.String(length=150), nullable=False),
    sa.Column('CompanyRegNo', sa.String(length=50), nullable=False),
    sa.Column('CompanyPhone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CompanyID')
    )
    op.create_table('Task',
    sa.Column('TaskID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TaskName', sa.String(length=150), nullable=False),
    sa.Column('RequiredCategory', sa.String(length=30), nullable=False),
    sa.Column('DefaultDuration', sa.Integer(), nullable=False),
    sa.Column('FrequencyType', sa.String(length=20), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('TaskID')
    )
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Fullname', sa.String(length=150), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('PhoneNo', sa.String(length=20), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', mssql.DATETIME2(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Attendance',
    sa.Column('AttendanceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AttendanceDate', sa.Date(), nullable=False),
    sa.Column('ClockInTime', mssql.DATETIME2(), nullable=True),
    sa.Column('ClockOutTime', mssql.DATETIME2(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('AttendanceID')
    )
    op.create_table('Zone',
    sa.Column('ZoneID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ZoneCode', sa.String(length=30), nullable=False),
    sa.Column('ZoneName', sa.String(length=255), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CampusCode', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['CampusCode'], ['Campus.CampusCode'], ),
    sa.PrimaryKeyConstraint('ZoneID'),
    sa.UniqueConstraint('ZoneCode')
    )
    op.create_table('Building',
    sa.Column('BuildingID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BuildingCode', sa.String(length=5), nullable=False),
    sa.Column('BuildingName', sa.String(length=255), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('ZoneID', sa.Integer(), nullable=True),
    sa.Column('CampusCode', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['CampusCode'], ['Campus.CampusCode'], ),
    sa.ForeignKeyConstraint(['ZoneID'], ['Zone.ZoneID'], ),
    sa.PrimaryKeyConstraint('BuildingID'),
    sa.UniqueConstraint('BuildingCode')
    )
    op.create_table('CompanyZone',
    sa.Column('CompanyID', sa.Integer(), nullable=False),
    sa.Column('ZoneID', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['CompanyID'], ['Company.CompanyID'], ),
    sa.ForeignKeyConstraint(['ZoneID'], ['Zone.ZoneID'], ),
    sa.PrimaryKeyConstraint('CompanyID', 'ZoneID')
    )
    op.create_table('GASchedule',
    sa.Column('ScheduleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ScheduleDate', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('TriggeredAt', mssql.DATETIME2(), nullable=True),
    sa.Column('CompletedAt', mssql.DATETIME2(), nullable=True),
    sa.Column('FitnessValue', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('Generations', sa.Integer(), nullable=True),
    sa.Column('TotalTasks', sa.Integer(), nullable=True),
    sa.Column('TotalCleaners', sa.Integer(), nullable=True),
    sa.Column('ZoneID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ZoneID'], ['Zone.ZoneID'], ),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    op.create_table('Staff',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Role', sa.String(length=20), nullable=False),
    sa.Column('Category', sa.String(length=30), nullable=False),
    sa.Column('CompanyID', sa.Integer(), nullable=False),
    sa.Column('ZoneID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CompanyID'], ['Company.CompanyID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.ForeignKeyConstraint(['ZoneID'], ['Zone.ZoneID'], ),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('Block',
    sa.Column('BlockID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BlockCode', sa.String(length=10), nullable=False),
    sa.Column('BlockName', sa.String(length=255), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('BuildingID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BuildingID'], ['Building.BuildingID'], ),
    sa.PrimaryKeyConstraint('BlockID'),
    sa.UniqueConstraint('BlockCode')
    )
    op.create_table('Floor',
    sa.Column('FloorID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FloorCode', sa.String(length=15), nullable=False),
    sa.Column('FloorName', sa.String(length=100), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('BlockID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BlockID'], ['Block.BlockID'], ),
    sa.PrimaryKeyConstraint('FloorID'),
    sa.UniqueConstraint('FloorCode')
    )
    op.create_table('Room',
    sa.Column('RoomID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RoomCode', sa.String(length=20), nullable=False),
    sa.Column('RoomName', sa.String(length=255), nullable=False),
    sa.Column('RoomType', sa.String(length=50), nullable=False),
    sa.Column('QRCode', sa.String(length=500), nullable=True),
    sa.Column('FloorID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FloorID'], ['Floor.FloorID'], ),
    sa.PrimaryKeyConstraint('RoomID'),
    sa.UniqueConstraint('RoomCode')
    )
    op.create_table('RoomTask',
    sa.Column('RoomTaskID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Slot', sa.String(length=20), nullable=True),
    sa.Column('RoomID', sa.Integer(), nullable=False),
    sa.Column('TaskID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoomID'], ['Room.RoomID'], ),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.TaskID'], ),
    sa.PrimaryKeyConstraint('RoomTaskID')
    )
    op.create_table('Assignment',
    sa.Column('AssignID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('StartTime', sa.Time(), nullable=True),
    sa.Column('EndTime', sa.Time(), nullable=True),
    sa.Column('CleanRating', sa.Integer(), nullable=True),
    sa.Column('RoomTaskID', sa.Integer(), nullable=False),
    sa.Column('ScheduleID', sa.Integer(), nullable=False),
    sa.Column('CleanerID', sa.Integer(), nullable=False),
    sa.Column('SupervisorID', sa.Integer(), nullable=True),
    sa.CheckConstraint('CleanRating BETWEEN 1 AND 3 OR CleanRating IS NULL', name='CK_CleanRating'),
    sa.ForeignKeyConstraint(['CleanerID'], ['Staff.UserID'], ),
    sa.ForeignKeyConstraint(['RoomTaskID'], ['RoomTask.RoomTaskID'], ),
    sa.ForeignKeyConstraint(['ScheduleID'], ['GASchedule.ScheduleID'], ),
    sa.ForeignKeyConstraint(['SupervisorID'], ['Staff.UserID'], ),
    sa.PrimaryKeyConstraint('AssignID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Assignment')
    op.drop_table('RoomTask')
    op.drop_table('Room')
    op.drop_table('Floor')
    op.drop_table('Block')
    op.drop_table('Staff')
    op.drop_table('GASchedule')
    op.drop_table('CompanyZone')
    op.drop_table('Building')
    op.drop_table('Zone')
    op.drop_table('Attendance')
    op.drop_table('User')
    op.drop_table('Task')
    op.drop_table('Company')
    op.drop_table('Campus')
    # ### end Alembic commands ###
