"""Added leaverequest and workorder table

Revision ID: a8bca5b4bed3
Revises: 67c7d2a7f6b4
Create Date: 2026-09-09 08:28:43.323624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'a8bca5b4bed3'
down_revision: Union[str, Sequence[str], None] = '67c7d2a7f6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LeaveRequest',
    sa.Column('LeaveID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.Column('LeaveType', sa.String(length=30), nullable=True),
    sa.Column('Reason', sa.String(length=255), nullable=True),
    sa.Column('Status', sa.String(length=20), server_default='Pending', nullable=False),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', mssql.DATETIME2(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('ApprovedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ApprovedBy'], ['User.UserID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('LeaveID')
    )
    op.create_table('WorkOrder',
    sa.Column('WorkOrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('WrID', sa.String(length=50), nullable=False),
    sa.Column('Requestor', sa.String(length=255), nullable=False),
    sa.Column('ProblemDesc', sa.String(length=500), nullable=True),
    sa.Column('Priority', sa.String(length=20), server_default='Normal', nullable=False),
    sa.Column('Status', sa.String(length=20), server_default='New', nullable=False),
    sa.Column('IssuedAt', mssql.DATETIME2(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('SpaceID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['SpaceID'], ['Space.SpaceID'], ),
    sa.PrimaryKeyConstraint('WorkOrderID'),
    sa.UniqueConstraint('WrID')
    )
    op.create_index('IX_WorkOrder_Space', 'WorkOrder', ['SpaceID'], unique=False)
    op.add_column('Assignment', sa.Column('WorkOrderID', sa.Integer(), nullable=True))
    op.alter_column('Assignment', 'TaskID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Assignment', 'ScheduleID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'Assignment', 'WorkOrder', ['WorkOrderID'], ['WorkOrderID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.alter_column('Assignment', 'ScheduleID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Assignment', 'TaskID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Assignment', 'WorkOrderID')
    op.drop_index('IX_WorkOrder_Space', table_name='WorkOrder')
    op.drop_table('WorkOrder')
    op.drop_table('LeaveRequest')
    # ### end Alembic commands ###
