"""Added room area and EPU for rooms

Revision ID: afbb91682c4f
Revises: 363f53b4921f
Create Date: 2026-08-02 16:37:27.276556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbb91682c4f'
down_revision: Union[str, Sequence[str], None] = '363f53b4921f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Room', sa.Column('RoomDescription', sa.String(length=255), nullable=True))
    op.add_column('Room', sa.Column('RoomArea', sa.Float(), nullable=False))
    op.add_column('Room', sa.Column('RoomEPU', sa.Float(), nullable=False))
    op.add_column('Room', sa.Column('IsActive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Room', 'IsActive')
    op.drop_column('Room', 'RoomEPU')
    op.drop_column('Room', 'RoomArea')
    op.drop_column('Room', 'RoomDescription')
    # ### end Alembic commands ###
