"""Added IsActive column to TaskGroupTask

Revision ID: b0cc54b2e688
Revises: a8bca5b4bed3
Create Date: 2026-09-17 15:02:40.937530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cc54b2e688'
down_revision: Union[str, Sequence[str], None] = 'a8bca5b4bed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TaskGroupTask', sa.Column('IsActive', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TaskGroupTask', 'IsActive')
    # ### end Alembic commands ###
