"""Added Taskgroup and TaskGroupTask table and removed RoomTask

Revision ID: b4cddb47d54f
Revises: ef197de7c430
Create Date: 2026-08-22 00:31:42.600903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cddb47d54f'
down_revision: Union[str, Sequence[str], None] = 'ef197de7c430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaskGroup',
    sa.Column('TaskGroupID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TaskGroupName', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('TaskGroupID')
    )
    op.create_table('TaskGroupTask',
    sa.Column('TaskGroupTaskID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FrequencyType', sa.String(length=20), nullable=False),
    sa.Column('FrequencyValue', sa.Integer(), nullable=True),
    sa.Column('Slot', sa.String(length=20), nullable=True),
    sa.Column('TaskGroupID', sa.Integer(), nullable=False),
    sa.Column('TaskID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['TaskGroupID'], ['TaskGroup.TaskGroupID'], ),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.TaskID'], ),
    sa.PrimaryKeyConstraint('TaskGroupTaskID'),
    sa.UniqueConstraint('TaskGroupID', 'TaskID', name='UQ_TaskGroupTask_Group_Task')
    )
    op.drop_table('RoomTask')
    op.add_column('Assignment', sa.Column('EstimatedDuration', sa.Integer(), nullable=True))
    op.add_column('Assignment', sa.Column('RoomID', sa.Integer(), nullable=False))
    op.add_column('Assignment', sa.Column('TaskID', sa.Integer(), nullable=False))
    op.create_index('IX_Assignment_Room_Task', 'Assignment', ['RoomID', 'TaskID'], unique=False)
    op.create_foreign_key(None, 'Assignment', 'Room', ['RoomID'], ['RoomID'])
    op.create_foreign_key(None, 'Assignment', 'Task', ['TaskID'], ['TaskID'])
    op.add_column('Room', sa.Column('TaskGroupID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Room', 'TaskGroup', ['TaskGroupID'], ['TaskGroupID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Room', type_='foreignkey')
    op.drop_column('Room', 'TaskGroupID')
    op.add_column('Assignment', sa.Column('RoomTaskID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.drop_constraint(None, 'Assignment', type_='foreignkey')
    op.create_foreign_key(op.f('FK__Assignmen__RoomT__634EBE90'), 'Assignment', 'RoomTask', ['RoomTaskID'], ['RoomTaskID'])
    op.drop_index('IX_Assignment_Room_Task', table_name='Assignment')
    op.drop_column('Assignment', 'TaskID')
    op.drop_column('Assignment', 'RoomID')
    op.drop_column('Assignment', 'EstimatedDuration')
    op.create_table('RoomTask',
    sa.Column('RoomTaskID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Slot', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('RoomID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TaskID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FrequencyType', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('EstimatedDuration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FrequencyValue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['RoomID'], ['Room.RoomID'], name=op.f('FK__RoomTask__RoomID__5D95E53A')),
    sa.ForeignKeyConstraint(['TaskID'], ['Task.TaskID'], name=op.f('FK__RoomTask__TaskID__5E8A0973')),
    sa.PrimaryKeyConstraint('RoomTaskID', name=op.f('PK__RoomTask__24D304F45C6ADF2A'))
    )
    op.drop_table('TaskGroupTask')
    op.drop_table('TaskGroup')
    # ### end Alembic commands ###
