"""Updated task and roomtask table

Revision ID: e0a99381c899
Revises: 54b88084d6e3
Create Date: 2026-08-16 00:06:09.657516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e0a99381c899'
down_revision: Union[str, Sequence[str], None] = '54b88084d6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('RoomTask', sa.Column('FrequencyType', sa.String(length=20), nullable=False))
    op.add_column('RoomTask', sa.Column('FreqnecyValue', sa.Integer(), nullable=True))
    op.add_column('RoomTask', sa.Column('EstimatedDuration', sa.Integer(), nullable=True))
    op.add_column('Task', sa.Column('TaskType', sa.String(length=30), nullable=False))
    op.add_column('Task', sa.Column('DurationBasis', sa.Integer(), nullable=False))
    op.drop_column('Task', 'DefaultDuration')
    op.drop_column('Task', 'FrequencyType')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('FrequencyType', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('Task', sa.Column('DefaultDuration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Task', 'DurationBasis')
    op.drop_column('Task', 'TaskType')
    op.drop_column('RoomTask', 'EstimatedDuration')
    op.drop_column('RoomTask', 'FreqnecyValue')
    op.drop_column('RoomTask', 'FrequencyType')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6195C76B42'))
    )
    # ### end Alembic commands ###
