"""Fixed wrong spelling of FrequencyValue in RoomTask

Revision ID: ef197de7c430
Revises: f871ca57400c
Create Date: 2026-08-20 20:09:47.137768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef197de7c430'
down_revision: Union[str, Sequence[str], None] = 'f871ca57400c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoomTask', sa.Column('FrequencyValue', sa.Integer(), nullable=True))
    op.drop_column('RoomTask', 'FreqnecyValue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoomTask', sa.Column('FreqnecyValue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('RoomTask', 'FrequencyValue')
    # ### end Alembic commands ###
